### ISSUE TITLE
Potential issue: global state and exception safety?

### ISSUE THREAD

**Issue by jimbo1qaz** [pr4bh4sh/python-delayed-assert#7]
What happens if test 1 uses `expect()` then crashes before calling `assert_expectations()`? I suspect test 1's expect failures will remain in the global variable, and get lumped into the next test's `assert_expectations()` output.

**Comment by pr4bh4sh** [comment]
@jimbo1qaz please review if this solves the problem.

**Comment by pr4bh4sh** [comment]
@jimbo1qaz  Please check #8 should fix this issue.
